version: '3.4'

services:

  input-parameters-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${GRAPH_CALCULATION_REDIS_PARAMETERS_DB:-parameters.data}
      - EventBusConnection=${GRAPH_CALCULATION_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GRAPH_CALCULATION_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GRAPH_CALCULATION_SERVICE_BUS_PASSWORD}
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80).

  fab-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${GRAPH_CALCULATION_REDIS_REUSULT_DB:-fab.data}
      - EventBusConnection=${GRAPH_CALCULATION_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GRAPH_CALCULATION_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GRAPH_CALCULATION_SERVICE_BUS_PASSWORD}
      - ParametersUrl=http://input-parameters-api
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80).  

  fx-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${GRAPH_CALCULATION_REDIS_REUSULT_DB:-fx.data}
      - EventBusConnection=${GRAPH_CALCULATION_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GRAPH_CALCULATION_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GRAPH_CALCULATION_SERVICE_BUS_PASSWORD}
      - ParametersUrl=http://input-parameters-api
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80). 

  fy-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${GRAPH_CALCULATION_REDIS_REUSULT_DB:-fy.data}
      - EventBusConnection=${GRAPH_CALCULATION_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GRAPH_CALCULATION_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GRAPH_CALCULATION_SERVICE_BUS_PASSWORD}
      - ParametersUrl=http://input-parameters-api
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80). 

  fcd-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${GRAPH_CALCULATION_REDIS_REUSULT_DB:-fcd.data}
      - EventBusConnection=${GRAPH_CALCULATION_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GRAPH_CALCULATION_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GRAPH_CALCULATION_SERVICE_BUS_PASSWORD}
      - ParametersUrl=http://input-parameters-api
      - FabUrl=http://fab-api
      - FyUrl=http://fy-api
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80). 

  fe-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${GRAPH_CALCULATION_REDIS_REUSULT_DB:-fe.data}
      - EventBusConnection=${GRAPH_CALCULATION_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GRAPH_CALCULATION_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GRAPH_CALCULATION_SERVICE_BUS_PASSWORD}
      - ParametersUrl=http://input-parameters-api
      - FcdUrl=http://fcd-api
      - FxUrl=http://fx-api
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80). 

  result-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${GRAPH_CALCULATION_REDIS_REUSULT_DB:-result.data}
      - EventBusConnection=${GRAPH_CALCULATION_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${GRAPH_CALCULATION_SERVICE_BUS_USERNAME}
      - EventBusPassword=${GRAPH_CALCULATION_SERVICE_BUS_PASSWORD}
      - FeUrl=http://fe-api
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80).  

  uimvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ParametersUrl=http://input-parameters-api
      - FabUrl=http://fab-api
      - FcdUrl=http://fcd-api
      - FeUrl=http://fe-api
      - FxUrl=http://fx-api
      - FyUrl=http://y-api
      - ResultUrl=http://result-api
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5600:80"  

  parametersdata.data:
    ports:
      - "6479:6479"    # Important: In a production environment your should remove the external port

  fabdata.data:
    ports:
      - "6481:6481"    # Important: In a production environment your should remove the external port

  fcddata.data:
    ports:
      - "6482:6482"    # Important: In a production environment your should remove the external port

  fedata.data:
    ports:
      - "6483:6483"    # Important: In a production environment your should remove the external port

  fxdata.data:
    ports:
      - "6484:6484"    # Important: In a production environment your should remove the external port

  fydata.data:
    ports:
      - "6485:6485"    # Important: In a production environment your should remove the external port

  resultdata.data:
    ports:
      - "6480:6480"    # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15772:15772"  # Important: In a production environment your should remove the external port
      - "5772:5772"    # Important: In a production environment your should remove the external port
